@echo off
echo ==========================================
echo      INSTALADOR DO SISTEMA SCFV
echo ==========================================
echo.
echo Instalando dependencias (Isso pode demorar um pouco)...
call npm install
echo.
echo ==========================================
echo      INSTALACAO CONCLUIDA!
echo ==========================================
echo.
echo Para abrir o sistema, execute o arquivo START.BAT
pause
